name:                xmonad-damianfral
version:             0.1.0.1
github:              "damianfral/xmonad-damianfral"
license:             BSD3
author:              "damianfral"
maintainer:          "huevofritopamojarpan@gmail.com"
copyright:           "2022 damianfral"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README

dependencies:

- base >= 4.7 && < 5
- containers
- xmonad
- xmonad-contrib
- optparse-generic

executables:

  xmonad-damianfral:
    main         : Main.hs
    source-dirs  : ./src

ghc-options:
- -Wall
- -fwarn-tabs
- -fwarn-incomplete-uni-patterns
- -fwarn-incomplete-record-updates
- -threaded
- -rtsopts -with-rtsopts=-N
